export { Buffer, BufferSet } from "./buffer.js";
export type { SelectionRange } from "./cell-grid.js";
export { CELL_SIZE, CellGrid, extractText, modPositive, normalizeSelection } from "./cell-grid.js";
export type { GestureConfig } from "./gesture-handler.js";
export { GestureHandler, GestureState } from "./gesture-handler.js";
export type { MouseEncoding, MouseProtocol } from "./parser/index.js";
export { VTParser } from "./parser/index.js";
export { Action, State, TABLE, unpackAction, unpackState } from "./parser/states.js";
export type { CursorState, SelectionState, TerminalOptions, Theme } from "./types.js";
export { DEFAULT_THEME, DirtyState } from "./types.js";
